#ifndef PARAMS_H
#define PARAMS_H

#define KYBER_N 256
#define KYBER_K 2
#define KYBER_ETA1 3
#define KYBER_ETA2 2
#define KYBER_EQ 12
#define KYBER_Q ((1 << KYBER_EQ) - 1) // 2^12
#define KYBER_du 10
#define KYBER_dv 4

#define KYBER_CIPHERBYTES ((KYBER_N * KYBER_K * KYBER_du + KYBER_N * KYBER_dv) / 8 + KYBER_SEEDBYTES)
#define KYBER_PUBLICKEYBYTES ((KYBER_N * KYBER_K * KYBER_EQ) / 8 + KYBER_SEEDBYTES)

#define KYBER_SEEDBYTES 32
#define KYBER_NOISE_SEEDBYTES 32
#define KYBER_KEYBYTES 32
#define KYBER_HASHBYTES 32

#define KYBER_POLYCOINBYTES_ETA1 (KYBER_ETA1 * KYBER_N / 4)
#define KYBER_POLYCOINBYTES_ETA2 (KYBER_ETA2 * KYBER_N / 4)

#define KYBER_POLYBYTES (13 * KYBER_N / 8)
#define KYBER_POLYVECBYTES (KYBER_K * KYBER_POLYBYTES)

#endif
